language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      env: MAPNIK_VERSION="2.3"
    - os: linux
      compiler: gcc
      env: MAPNIK_VERSION="2.3"

before_install:
 - sudo apt-add-repository --yes ppa:mapnik/nightly-${MAPNIK_VERSION}
 - sudo apt-get update -y

install:
 - sudo apt-get -y install build-essential make libmapnik=${MAPNIK_VERSION}* mapnik-utils=${MAPNIK_VERSION}* libmapnik-dev=${MAPNIK_VERSION}* mapnik-input-plugin*=${MAPNIK_VERSION}*

script:
 - make test/c-api-test && ./test/c-api-test
 - make test/c-api-c99-test && ./test/c-api-c99-test

